name: Ejecutar El Cazador BCV

on:
  schedule:
    # Se ejecuta en los minutos 3, 11, 19, 27, 35, 43, 51 (esquiva las horas en punto)
    - cron: '3/8 19-23 * * 1-5'
  workflow_dispatch: # Permite ejecutarlo manualmente con un botón en cualquier momento
  
jobs:
  ejecutar-cazador:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Correr El Cazador
      env:
        URL_BOT_RAILWAY_SECUNDARIO: ${{ secrets.URL_BOT_RAILWAY_SECUNDARIO }}
        URL_BOT_RAILWAY: ${{ secrets.URL_BOT_RAILWAY }}
        CLAVE_SECRETA_BCV: ${{ secrets.CLAVE_SECRETA_BCV }}
      run: |
        python cazador.py 

